qs

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -190,6 +190,8 @@ stages:
           matrix:
             IT_es91x:
               ROR_TASK: integration_es91x
+            IT_es90x:
+              ROR_TASK: integration_es90x
       - job:
         condition:
           and(
@@ -298,8 +300,6 @@ stages:
           matrix:
             IT_es91x:
               ROR_TASK: integration_es91x
-            IT_es90x:
-              ROR_TASK: integration_es90x
       - job:
         condition:
           and(
@@ -309,40 +309,84 @@ stages:
             ne(variables.isMaster, true),
             not(and(eq(variables['Build.Reason'], 'Manual'), eq('${{ parameters.actionToPerform }}', 'run_all_tests')))
           )
-        container: openjdk:22-slim
         timeoutInMinutes: 120
+        pool:
+          vmImage: 'windows-2025'
         steps:
           - checkout: self
             fetchDepth: 1
             clean: false
             persistCredentials: true
-          - script: |
-              # Translate back env vars to avoid cyclical reference :/
-              export aws_access_key_id=$var_aws_access_key_id
-              export aws_secret_access_key=$var_aws_secret_access_key
-
-              echo "[TEST] executing ROR_TASK = $ROR_TASK"
-              ci/run-pipeline.sh
-            env:
-              var_aws_access_key_id: $(aws_access_key_id)
-              var_aws_secret_access_key: $(aws_secret_access_key)
+          - task: JavaToolInstaller@0
+            displayName: Switch to Java 22
+            inputs:
+              versionSpec: '22'
+              jdkArchitectureOption: 'x64'
+              jdkSourceOption: 'PreInstalled'
+          - powershell: |
+                    docker ps
+                    Write-Host ">>> $env:ES_MODULE => Running testcontainers.."
+                    .\gradlew integration-tests:test "-PesModule=$env:ES_MODULE"
+                    if ($LASTEXITCODE -ne 0) {
+                      Get-ChildItem -Recurse -Filter *hs_err* | ForEach-Object {
+                        Get-Content $_.FullName
+                      }
+                      exit 1
+                    }
           - task: PublishTestResults@2
             condition: failed()
             inputs:
-              testRunTitle: "$(ROR_TASK) results"
+              testRunTitle: "$(Windows ES_MODULE) results"
               testResultsFiles: "**/TEST*xml"
               mergeTestResults: true
         strategy:
           maxParallel: 99
           matrix:
-            IT_es818x:
-              ROR_TASK: integration_es818x
-            IT_es816x:
-              ROR_TASK: integration_es816x
-            IT_es810x:
-              ROR_TASK: integration_es810x
-            IT_es80x:
-              ROR_TASK: integration_es80x
+            IT_es91x:
+              ES_MODULE: es91x
+#       - job:
+#         condition:
+#           and(
+#             succeeded(),
+#             ne(variables.isEpic, true),
+#             ne(variables.isDevelop, true),
+#             ne(variables.isMaster, true),
+#             not(and(eq(variables['Build.Reason'], 'Manual'), eq('${{ parameters.actionToPerform }}', 'run_all_tests')))
+#           )
+#         container: openjdk:22-slim
+#         timeoutInMinutes: 120
+#         steps:
+#           - checkout: self
+#             fetchDepth: 1
+#             clean: false
+#             persistCredentials: true
+#           - script: |
+#               # Translate back env vars to avoid cyclical reference :/
+#               export aws_access_key_id=$var_aws_access_key_id
+#               export aws_secret_access_key=$var_aws_secret_access_key
+#
+#               echo "[TEST] executing ROR_TASK = $ROR_TASK"
+#               ci/run-pipeline.sh
+#             env:
+#               var_aws_access_key_id: $(aws_access_key_id)
+#               var_aws_secret_access_key: $(aws_secret_access_key)
+#           - task: PublishTestResults@2
+#             condition: failed()
+#             inputs:
+#               testRunTitle: "$(ROR_TASK) results"
+#               testResultsFiles: "**/TEST*xml"
+#               mergeTestResults: true
+#         strategy:
+#           maxParallel: 99
+#           matrix:
+#             IT_es818x:
+#               ROR_TASK: integration_es818x
+#             IT_es816x:
+#               ROR_TASK: integration_es816x
+#             IT_es810x:
+#               ROR_TASK: integration_es810x
+#             IT_es80x:
+#               ROR_TASK: integration_es80x
       - job:
         condition:
           and(
@@ -405,49 +449,49 @@ stages:
               ROR_TASK: integration_es70x
             IT_es67x:
               ROR_TASK: integration_es67x
-      - job:
-        condition:
-          and(
-            succeeded(),
-            ne(variables.isEpic, true),
-            ne(variables.isDevelop, true),
-            ne(variables.isMaster, true),
-            not(and(eq(variables['Build.Reason'], 'Manual'), eq('${{ parameters.actionToPerform }}', 'run_all_tests')))
-          )
-        timeoutInMinutes: 120
-        steps:
-          - checkout: self
-            fetchDepth: 1
-            clean: false
-            persistCredentials: true
-          - script: |
-              # Translate back env vars to avoid cyclical reference :/
-              export aws_access_key_id=$var_aws_access_key_id
-              export aws_secret_access_key=$var_aws_secret_access_key
-
-              echo "[TEST] executing ROR_TASK = $ROR_TASK"
-              ci/run-pipeline.sh
-            env:
-              var_aws_access_key_id: $(aws_access_key_id)
-              var_aws_secret_access_key: $(aws_secret_access_key)
-          - task: PublishTestResults@2
-            condition: failed()
-            inputs:
-              testRunTitle: "$(ROR_TASK) results"
-              testResultsFiles: "**/TEST*xml"
-              mergeTestResults: true
-        strategy:
-          maxParallel: 99
-          matrix:
-            IT_es717x:
-              ROR_TASK: integration_es717x
-            IT_es710x:
-              ROR_TASK: integration_es710x
-            IT_es70x:
-              ROR_TASK: integration_es70x
-            IT_es67x:
-              ROR_TASK: integration_es67x
-
+#       - job:
+#         condition:
+#           and(
+#             succeeded(),
+#             ne(variables.isEpic, true),
+#             ne(variables.isDevelop, true),
+#             ne(variables.isMaster, true),
+#             not(and(eq(variables['Build.Reason'], 'Manual'), eq('${{ parameters.actionToPerform }}', 'run_all_tests')))
+#           )
+#         timeoutInMinutes: 120
+#         steps:
+#           - checkout: self
+#             fetchDepth: 1
+#             clean: false
+#             persistCredentials: true
+#           - script: |
+#               # Translate back env vars to avoid cyclical reference :/
+#               export aws_access_key_id=$var_aws_access_key_id
+#               export aws_secret_access_key=$var_aws_secret_access_key
+#
+#               echo "[TEST] executing ROR_TASK = $ROR_TASK"
+#               ci/run-pipeline.sh
+#             env:
+#               var_aws_access_key_id: $(aws_access_key_id)
+#               var_aws_secret_access_key: $(aws_secret_access_key)
+#           - task: PublishTestResults@2
+#             condition: failed()
+#             inputs:
+#               testRunTitle: "$(ROR_TASK) results"
+#               testResultsFiles: "**/TEST*xml"
+#               mergeTestResults: true
+#         strategy:
+#           maxParallel: 99
+#           matrix:
+#             IT_es717x:
+#               ROR_TASK: integration_es717x
+#             IT_es710x:
+#               ROR_TASK: integration_es710x
+#             IT_es70x:
+#               ROR_TASK: integration_es70x
+#             IT_es67x:
+#               ROR_TASK: integration_es67x
+#
   - stage: BUILD_ROR
     displayName: 'Build ROR plugins'
     dependsOn:
